name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      BUILD_VERSION:
        description: App version
        default: "1.0.0"
        required: true
      RUN_SECURITY_SCAN:
        description: Run security scan
        type: boolean
        default: true
      DEPLOY_TARGET:
        description: Where to deploy
        type: choice
        options: [staging, production, both]
        default: both

env:
  BUILD_VERSION: ${{ github.event.inputs.BUILD_VERSION || '1.0.0' }}
  RUN_SECURITY_SCAN: ${{ github.event.inputs.RUN_SECURITY_SCAN || 'true' }}
  DEPLOY_TARGET: ${{ github.event.inputs.DEPLOY_TARGET || 'both' }}

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo build info
        run: |
          echo "Fetching source code"
          echo "Building version $BUILD_VERSION"
          echo "RUN_SECURITY_SCAN=$RUN_SECURITY_SCAN"
          echo "DEPLOY_TARGET=$DEPLOY_TARGET"

      - name: Build
        run: |
          echo "Build"
          echo "Compile"

      - name: Unit test
        run: echo "Run unit tests"

      - name: Integration test
        run: echo "Run integration tests"

      - name: Security scan
        if: ${{ env.RUN_SECURITY_SCAN == 'true' }}
        run: echo "Security scan"

      - name: Deploy to staging
        if: ${{ env.DEPLOY_TARGET == 'staging' || env.DEPLOY_TARGET == 'both' }}
        env:
          DEPLOY_API_TOKE
